{% set name = "vaex-ml" %}
{% set version = "0.8.0" %}
{% set sha256 = "ac3da27a272222ff39626104e845b35b0b55b486a8a83535c2f5712e513220cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - vaex-core >=1.0.0,<2
    - numba
    - traitlets
    - jinja2

test:
  imports:
    - vaex.ml

about:
  home: https://www.github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Machine learning support for vaex
  description: |
    Wrappers for various machine learning libraries to make them integrate into
    vaex.

extra:
  recipe-maintainers:
    - maartenbreddels
